services:
  - name: backend
    plan: starter
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start

  - name: frontend
    plan: starter
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
